version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
      timezone: America/New_York
    open-pull-requests-limit: 3
    groups:
      storybook:
        patterns:
          - '@storybook*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
      tinacms:
        patterns:
          - 'tinacms'
          - '@tinacms*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
