name: 'Combine Dependabot PRs'
on:
  workflow_dispatch:

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: maadhattah/combine-dependabot-prs@v1.0.5
        with:
          combineBranchName: 'update-dependencies'
          baseBranch: 'main'
