name: 'Combine Dependabot PRs'
on:
  workflow_dispatch:
    inputs:
      branchPrefix:
        description: 'Branch prefix to find combinable PRs based on'
        required: true
        default: 'dependabot'
      mustBeGreen:
        description: 'Only combine PRs that are green (status is success)'
        required: true
        default: 'true'
      combineBranchName:
        description: 'Name of the branch to combine PRs into'
        required: true
        default: 'combined-prs'
      ignoreLabel:
        description: 'Exclude PRs with this label'
        required: true
        default: 'nocombine'
      baseBranch:
        description: 'Branch to PR into'
        required: true
        default: 'main'
jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: maadhattah/combine-dependabot-prs@initial-implementation
